---
title: "Class 10"
author: "Peter Franz"
date: "2026-09-28"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `robotstxt` example: MU bulletin

In the chunk below, we used the [robotstxt package](https://github.com/ropensci/robotstxt) to check if we are allowed to write a program that scrapes the page:
<https://bulletin.miamioh.edu/courses-instruction/isa/>

```{r bulletin}
robotstxt::paths_allowed(
  paths = "/courses-instruction/isa/",
  domain = "bulletin.miamioh.edu",
  bot = "*"
)
```

The TRUE above
```{r check_3_sites}
robotstxt::paths_allowed(
  paths = "/wiki/Miami_Redhawks_football/",
  domain = "en.wikipedia.org",
  bot = "*"
)

# in some cases, the robotstxt provides inconsistent answers
# typically, you get a warning with the answer that is incorrect
# solution: drop the trailing slash from the URL
# even better check with the robots.txt (which is the ground truth)
robotstxt::paths_allowed(
  paths = "/jobs/",
  domain = "www.linkedin.com",
  bot = "*"
)

robotstxt::paths_allowed(
  paths = c("/jobs","/viewjob"),
  domain = "www.indeed.com",
  bot = "*"
)


```

## Scrape Miami's bulletin for ISA

```{r bulletin_scrape}
# checking whether we are allowed to scrape this info
# This was done above and found to be True

#I will load the backend of the HTML into R using
# [a] rvest::read_html() | sometimes rvest::read_html_live() if the pae has some dynamic content
# [b] in some cases, we will craft this as a request as shown in:
# slides httr2::request() > .... > httr2::resp_body_html

isa_courses_in_r = rvest::read_html("https://bulletin.miamioh.edu/courses-instruction/isa/")

# we will extract the course titles, which we can do in a single pipeline
# given that they look the same on the rendered web page in Chrome
# (bolded, same font size, same font type)

### CSS selector was obtained by:
# [a] highlighting what we wanted to pull (ISA 401 course title) -> right click, inspect -->
# right click Copy -> copy selector
# [b] from this specific example, we were able to get just the title for ISA 401 (because we had `:nth-child(24)`) -> if you were to drop it --> you get all the course titles
isa_courses_in_r |>
  rvest::html_elements("#sc_sccoursedescs > div:nth-child(24) > p.courseblocktitle > strong") |>
  rvest::html_text2() -> isa_titles


# course descriptions [using selector gadget, which doesn't always work]
isa_courses_in_r |>
  rvest::html_elements(".courseblockdesc") |>
  rvest::html_text2() -> isa_desc

df = data.frame(title = isa_titles, dsecription = isa_desc)
```


